import { useState } from 'react';
import { animeConfig } from '../../data/anime';
import { currentDailyStreak } from '../../quiz/profileResult';
import Button from '../Button';
import Card from '../Card';
export default function QuizSetup({ user, initialMode, today, history, onStart, onOpen, disabled }) {
  const [mode, setMode] = useState(initialMode), [anime, setAnime] = useState('all'), [difficulty, setDifficulty] = useState('all');
  const daily = history.find(item => item.mode === 'daily' && item.date === today);
  return <div className="quiz-setup"><Card className="quiz-panel"><span className="eyebrow">CHOOSE YOUR CHALLENGE</span><h2>HOW MUCH DO YOU KNOW?</h2><form onSubmit={event => { event.preventDefault(); onStart({ mode, anime, difficulty }); }}>
    <label>Mode<select value={mode} onChange={event => setMode(event.target.value)}><option value="classic">Classic · 10 questions</option><option value="blitz">Timed Blitz · 60 seconds</option><option value="daily">Daily Challenge · 5 questions</option></select></label>
    {mode !== 'daily' && <><label>Anime<select value={anime} onChange={event => setAnime(event.target.value)}><option value="all">Mixed · all three worlds</option>{animeConfig.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Difficulty<select value={difficulty} onChange={event => setDifficulty(event.target.value)}>{['all', 'easy', 'medium', 'hard'].map(value => <option key={value} value={value}>{value === 'all' ? 'All difficulties' : value[0].toUpperCase() + value.slice(1)}</option>)}</select></label></>}
    <p className="quiz-note">{mode === 'daily' ? `Today: ${today}. Five shared mixed questions. One attempt per day, reset at midnight India time. Answers save as you play; an unfinished attempt can resume.` : mode === 'blitz' ? 'The clock keeps running during explanations and after a reload. Correct streaks raise your multiplier every 3 answers, up to ×4. Finish early if you clear the question pool.' : 'Ten shuffled questions. No timer. Read each explanation, then continue.'}</p>
    <Button type="submit" disabled={disabled}>{mode === 'daily' && daily ? daily.status === 'complete' ? 'View today’s result' : 'Resume daily challenge' : 'Start quiz'}</Button>
  </form></Card><Card className="quiz-panel"><span className="eyebrow">YOUR KNOWLEDGE ARC</span><h2>{user ? user.username : 'GUEST SCHOLAR'}</h2><dl className="quiz-totals"><div><dt>Quiz XP</dt><dd>{user?.quizStats.xp ?? '—'}</dd></div><div><dt>Best accuracy</dt><dd>{user?.quizStats.bestScore ?? 0}%</dd></div><div><dt>Daily streak</dt><dd>{user ? currentDailyStreak(user, today) : '—'}</dd></div></dl><p className="quiz-note">{user ? 'XP, best accuracy, mode high scores and daily streaks save to your profile.' : 'Guest attempts and results save in this browser. Log in before starting to earn profile XP, daily streaks and achievements.'}</p>{!user && <Button to="/login" variant="secondary">Log in for profile progress</Button>}<p className="quiz-note">90 questions: 30 Naruto, 30 One Piece, 30 Bleach. Manga facts only, with spoilers through the accepted cutoffs. Easy / medium / hard are editorial labels.</p><p className="quiz-note">Correct answers: easy 100, medium 150, hard 200 points. Every 10 points earns 1 XP. Daily streaks count completed challenge days, regardless of score.</p></Card>
    <Card className="quiz-panel quiz-history"><h2>RECENT ATTEMPTS</h2>{!history.length && <p>No attempts yet. Pick a world and begin.</p>}<ul>{history.map(item => <li key={item.id}><div><strong>{item.mode === 'daily' ? `Daily · ${item.date}` : `${item.mode} · ${item.anime} · ${item.difficulty}`}</strong><span>{item.answers.length} / {item.questions.length} answered · {item.status === 'active' ? 'In progress' : item.saved ? 'Saved result' : 'Profile save pending'}</span></div><Button disabled={disabled} variant="secondary" onClick={() => onOpen(item)}>{item.status === 'active' ? 'Resume' : item.saved ? 'View result' : 'Finish saving'}</Button></li>)}</ul></Card></div>;
}
