import { useState } from 'react';
import { animeConfig } from '../../data/anime';
import { boardLabel, gameNames } from '../../minigames/config';
import Button from '../Button';
import Card from '../Card';
export default function GameSetup({ user, history, highScores, initialSettings, disabled, onStart, onOpen }) {
  const [mode, setMode] = useState(initialSettings?.mode ?? 'move'), [anime, setAnime] = useState(initialSettings?.anime ?? 'all');
  const [hard, setHard] = useState(initialSettings?.hard ?? false), [answerMode, setAnswerMode] = useState(initialSettings?.answerMode ?? 'choice'), [streak, setStreak] = useState(initialSettings?.streak ?? true);
  return <div className="mini-setup"><Card className="mini-panel"><span className="eyebrow">PICK YOUR GAME</span><h2>KNOW YOUR FIGHTERS.</h2><form onSubmit={event => { event.preventDefault(); onStart({ mode, anime, hard: mode === 'move' && hard, answerMode: mode === 'move' ? answerMode : 'choice', streak: mode === 'power' && streak }); }}>
    <label>Game<select value={mode} onChange={event => setMode(event.target.value)}>{Object.entries(gameNames).map(([value, name]) => <option key={value} value={value}>{name}</option>)}</select></label><label>Anime<select value={anime} onChange={event => setAnime(event.target.value)}><option value="all">All worlds</option>{animeConfig.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
    {mode === 'move' && <><label>Answer style<select value={answerMode} onChange={event => setAnswerMode(event.target.value)}><option value="choice">Four choices</option><option value="typed">Type a name</option></select></label><label className="mini-check"><input type="checkbox" checked={hard} onChange={event => setHard(event.target.checked)} />Hard mode · unnamed stat bars</label></>}
    {mode === 'power' && <label className="mini-check"><input type="checkbox" checked={streak} onChange={event => setStreak(event.target.checked)} />Streak scoring · capped ×4 multiplier</label>}
    <p className="mini-note">{mode === 'move' ? hard ? 'Identify a fixed peak fighter from eight ratings. This tests familiarity with this site’s ratings. 45 seconds, 150 points per correct answer.' : 'Identify a fighter from 2–3 signature moves and ability tags. 30 seconds, 100 points per correct answer. Unique first names and small typos work in typed mode; shared surnames need a full name.' : mode === 'clue' ? 'Reveal up to three clues. One guess per round. Correct answers earn 300 / 200 / 100 points for one / two / three clues. 30 seconds per round.' : 'Decide whether the challenger’s peak power is higher or lower than the reference. Equal scores are excluded. 30 seconds per round; streak mode increases points every three correct answers and resets on a miss.'}</p><Button type="submit" disabled={disabled}>Start game</Button>
  </form></Card><Card className="mini-panel"><span className="eyebrow">TEN ROUNDS. THREE WAYS TO PLAY.</span><h2>{user ? user.username : 'GUEST PLAYER'}</h2><p>Each game uses locked peak snapshots from the accepted roster. No artwork is needed.</p><p className="mini-note">Scores are separate by game, anime filter and rules. Sign in before starting to add game records to your profile. Guests keep high scores in this browser too.</p><p className="mini-note">Save and leave to resume later. An unanswered round’s timer keeps running; reading feedback does not consume the next round’s time. Game scores do not change battle rank or quiz XP.</p><p className="mini-note">Power and stat ratings are fan-made game estimates. Full roster calibration remains deferred.</p><Button to="/characters" variant="secondary">Study the roster</Button></Card>
    <Card className="mini-panel mini-wide"><h2>HIGH SCORES</h2>{!Object.keys(highScores).length && <p>Finish a game to set your first score.</p>}<ul className="mini-score-list">{Object.entries(highScores).sort(([a], [b]) => a.localeCompare(b)).map(([key, score]) => <li key={key}><span>{boardLabel(key)}</span><strong>{score}</strong></li>)}</ul></Card>
    <Card className="mini-panel mini-wide"><h2>RECENT GAMES</h2>{!history.length && <p>No games yet. Choose a challenge above.</p>}<ul className="mini-history">{history.map(session => <li key={session.id}><div><strong>{boardLabel(session.board)}</strong><span>{session.answers.length} / 10 answered · {session.status === 'active' ? 'In progress' : session.saved ? 'Saved result' : 'Save pending'}</span></div><Button variant="secondary" disabled={disabled} onClick={() => onOpen(session)}>{session.status === 'active' ? 'Resume' : session.saved ? 'View result' : 'Finish saving'}</Button></li>)}</ul></Card></div>;
}
