import { motion } from 'framer-motion';
import { Swords, Sparkles, LockKeyhole, Flame, Anchor, Sword, CircleHelp, Zap } from 'lucide-react';
import { Link } from 'react-router-dom';
import { animeConfig, animeTheme } from '../data/anime';
import Button from '../components/Button';
import Badge from '../components/Badge';
import Card from '../components/Card';
const icons = { naruto: Flame, onepiece: Anchor, bleach: Sword };
export default function Home() {
  return <div className="home container"><section className="hero"><div className="hero-orbit" aria-hidden="true" /><motion.div className="hero-content" initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}><Badge><Sparkles size={13} /> THREE WORLDS. ONE PLAYGROUND.</Badge><h1>YOUR ANIME.<br />YOUR <span>SHOWDOWN.</span></h1><p>Shinobi, pirates, Soul Reapers.<br className="mobile-break" /> Pick your world. Bring your competitive side.</p><div className="hero-actions"><Button to="/battle"><Swords size={19} /> Enter the arena</Button><Button to="/quizzes" variant="secondary"><CircleHelp size={19} /> Test your knowledge</Button></div><div className="hero-meta"><span>01 / BATTLE</span><span>02 / QUIZ</span><span>03 / GUESS</span></div></motion.div><div className="hero-type" aria-hidden="true"><span>VS</span><small>THE CROSSOVER<br />STARTS HERE</small></div></section><section className="worlds" aria-labelledby="worlds-title"><div className="section-heading"><div><span className="eyebrow">CHOOSE YOUR UNIVERSE</span><h2 id="worlds-title">THREE WORLDS. <span>ENDLESS RIVALRIES.</span></h2></div><span className="section-note">The launch lineup</span></div><div className="portal-grid">{animeConfig.map((anime, index) => { const Icon = icons[anime.id]; return <motion.div key={anime.id} initial={{ opacity: 0, y: 12 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.08 }}><Link to={`/anime/${anime.id}`} className={`portal portal-${anime.id}`} style={animeTheme(anime)}><div className="portal-top"><span><Icon size={17} /> {anime.label}</span><span>0{index + 1}</span></div><div className="portal-motif" aria-hidden="true">{anime.motif}</div><div className="portal-content"><span className="portal-subtitle">{anime.subtitle}</span><h3>{anime.name}</h3><p>{anime.description}</p><span className="portal-link">Explore world <span>＋</span></span></div></Link></motion.div>; })}</div></section><section className="feature-grid" aria-label="More ways to play"><Card className="arena-banner"><div className="arena-symbol" aria-hidden="true"><Swords strokeWidth={1} /></div><div className="banner-content"><Badge>THE MAIN EVENT</Badge><h2>SETTLE IT<br /><span>IN THE ARENA.</span></h2><p>Five fighters. Five rounds. One winner.<br />Your dream crossover is on the horizon.</p><Button to="/battle"><Swords size={17} /> Explore Battle Arena</Button></div></Card><Card className="daily-card"><div className="daily-heading"><span className="daily-icon"><Zap size={23} /></span><Badge><LockKeyhole size={12} /> COMING SOON</Badge></div><span className="eyebrow">A LITTLE EVERY DAY</span><h2>DAILY<br />CHALLENGE</h2><p>Five questions. Three anime.<br />How well do you know your worlds?</p><div className="daily-bottom"><span>New challenge every day</span><span className="locked">Unlocks in Phase 6</span></div></Card></section></div>;
}
